twitter_clone/twitter_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from twitter_profile.views import frontpage, signout, profile, profile_tabs, profile_settings, settings_tabs
from tweet.views import follows, followers, follow, stopfollow, status, feed, like, reply


urlpatterns = [
  path('', frontpage, name='frontpage'),
  path('feed/', feed, name='feed'),
  path('signout/', signout, name='signout'),
  path('admin/', admin.site.urls),
  path('settings/', profile_settings, name='profile_settings'),
  path('settings/<str:tab>', settings_tabs, name='settings_tabs'),
  path('reply/', reply, name='reply'),
  path('reply/<int:user>/<int:tweet>', reply, name='reply'),
  path('<str:username>/follows/', follows, name='follows'),
  path('<str:username>/followers/', followers, name='followers'),
  path('<str:username>/follow/', follow, name='follow'),
  path('<str:username>/stopfollow/', stopfollow, name='stopfollow'),
  path('<str:username>/status/<int:id>/', status, name='status'),
  path('<str:username>/status/<int:id>/like', like, name='like'),
  path('<str:username>/', profile, name='profile'),
  path('<str:username>/<str:tab>', profile_tabs, name='profile_tabs'),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_clone/twitter_profile/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
import sys

class TwitterProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    username = models.CharField(max_length=50, blank=True)
    biography = models.CharField(max_length=160, blank=True)
    profile_picture = models.ImageField(upload_to='profile/', blank=True)
    profile_banner = models.ImageField(upload_to='profile/', blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    private = models.BooleanField(default=False)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False, blank=True)

    def crop_profile_picture(self,photo,x,y,w,h):
        image = Image.open(photo)
        output = BytesIO()
        image = image.crop((x, y, w+x, h+y))
        image = image.resize((400, 400), Image.ANTIALIAS)
        image = image.convert('RGB')
        image.save(output,format='JPEG',quality=100)
        output.seek(0)
        self.profile_picture = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.profile_picture.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super(TwitterProfile,self).save()

    def crop_banner_picture(self,photo,x,y,w,h):
        image = Image.open(photo)
        output = BytesIO()
        image = image.crop((x, y, w+x, h+y))
        image = image.resize((1500, 500), Image.ANTIALIAS)
        image = image.convert('RGB')
        image.save(output,format='JPEG',quality=100)
        output.seek(0)
        self.profile_banner = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.profile_banner.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super(TwitterProfile,self).save()

User.twitterprofile = property(lambda u: TwitterProfile.objects.get_or_create(user=u)[0])

twitter_clone/twitter_profile/forms.py
# Import django forms and models
from PIL import Image
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.utils.html import strip_tags
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import RegexValidator
from .models import TwitterProfile

class PersonalInfoForm(forms.Form):
    banner_picture = forms.ImageField(required=False,label="",widget=forms.FileInput(attrs={'accept': 'image/*', '@change':'onBannerChange', 'class':'btn btn-primary'}))
    profile_picture = forms.ImageField(required=False,label="",widget=forms.FileInput(attrs={'accept': 'image/*', '@change':'onProfileChange', 'class':'btn btn-primary'}))
    username = forms.CharField(label="", max_length=50, widget=forms.widgets.TextInput(attrs={':maxlength':'max_user', 'v-model':'username','placeholder': 'Add your name', 'class': 'form-control', '@focus':'user_focus = true', '@blur':'user_focus = false'}))
    biography = forms.CharField(label="", max_length=160, widget=forms.widgets.TextInput(attrs={':maxlength':'max_bio', 'v-model':'bio','placeholder': 'Add your bio', 'class': 'form-control', '@focus':'bio_focus = true', '@blur':'bio_focus = false'}))
    p_x = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'profile_coordinates.left'}))
    p_y = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'profile_coordinates.top'}))
    p_width = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'profile_coordinates.width'}))
    p_height = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'profile_coordinates.height'}))
    b_x = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'banner_coordinates.left'}))
    b_y = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'banner_coordinates.top'}))
    b_width = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'banner_coordinates.width'}))
    b_height = forms.FloatField(required=False, widget=forms.HiddenInput(attrs={'v-model':'banner_coordinates.height'}))

    class Meta:
        model = TwitterProfile
        fields = ('banner_picture', 'profile_picture', 'username', 'biography', 'p_x', 'p_y', 'p_width', 'p_height', 'b_x', 'b_y', 'b_width', 'b_height')



class SignupForm(UserCreationForm):
    user_regex = RegexValidator(regex=r'^[a-zA-Z0-9_]+$', message="Username must only contain only alphanumerical characters and underscores. ABC, abc, 123, _")
    email = forms.EmailField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}))
    username = forms.CharField(validators=[user_regex], max_length=15, widget=forms.widgets.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    name = forms.CharField(max_length=50, widget=forms.widgets.TextInput(attrs={'placeholder': 'Screen name', 'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password Confirmation', 'class': 'form-control'}))

    class Meta:
        fields = ['email', 'username', 'name', 'first_name', 'last_name', 'password1', 'password2']
        model = User

class SigninForm(AuthenticationForm):
  username = forms.CharField(widget=forms.widgets.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
  password = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))

class ChangeUsernameForm(forms.Form):
    username = forms.CharField(label="Username", widget=forms.widgets.TextInput(attrs={'v-model':'message','placeholder': 'Choose a username', 'class': 'form-control'}))

    class Meta:
        fields = ['username']
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username) #this raises an ObjectDoesNotExist exception if it doesn't find a user with that username
        except ObjectDoesNotExist:
            return username #if username doesn't exist
        raise forms.ValidationError('Username is already taken.')

class ChangePasswordForm(forms.Form):
    password1 = forms.CharField(label="New Password", widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    password2 = forms.CharField(label="New Password Confirmation", widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password Confirmation', 'class': 'form-control'}))

    class Meta:
        fields = ['password1', 'password2']

class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.widgets.TextInput(attrs={'v-model':'message','placeholder': 'Choose an email', 'class': 'form-control'}))

    class Meta:
        fields = ['email']
    
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email) #this raises an ObjectDoesNotExist exception if it doesn't find a user with that email
        except ObjectDoesNotExist:
            return email #if email doesn't exist
        raise forms.ValidationError('Email is already being used.')

class ChangePhoneForm(forms.Form):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$', message="Phone number must be entered in the format: '(999) 999-9999'. Up to 10 digits allowed.")
    phone_number = forms.CharField(validators=[phone_regex], label="Phone Number", widget=forms.widgets.TextInput(attrs={'v-model':'message','placeholder': '(xxx) xxx-xxxx', 'class': 'form-control'}))

    class Meta:
        fields = ['phone_number']

 

twitter_clone/twitter_profile/views.py
# Import django and models

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from twitter_profile.forms import SignupForm, SigninForm, ChangeUsernameForm, ChangeEmailForm, ChangePhoneForm, ChangePasswordForm, PersonalInfoForm
from tweet.forms import TweetForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound
from tweet.models import Tweet

# Views

@login_required
def profile(request, username):
  if request.user.is_authenticated:
    user = User.objects.get(username=username)
    
    if request.method == 'POST':
      if 'tweetform' in request.POST:
        form = TweetForm(data=request.POST)
        infoform = PersonalInfoForm()

        if form.is_valid():
          tweet = form.save(commit=False)
          tweet.user = request.user
          tweet.save()
          
          redirecturl = request.POST.get('redirect', '/')

          return redirect(redirecturl)

      else:
        infoform = PersonalInfoForm(request.POST, request.FILES)
        form = TweetForm()
        if infoform.is_valid():
          profile = request.user.twitterprofile
          if infoform.cleaned_data.get('profile_picture'):
            photo = infoform.cleaned_data.get('profile_picture')
            x = infoform.cleaned_data.get('p_x')
            y = infoform.cleaned_data.get('p_y')
            w = infoform.cleaned_data.get('p_width')
            h = infoform.cleaned_data.get('p_height')
            profile.crop_profile_picture(photo,x,y,w,h)
          if infoform.cleaned_data.get('banner_picture'):
            photo = infoform.cleaned_data.get('banner_picture')
            x = infoform.cleaned_data.get('b_x')
            y = infoform.cleaned_data.get('b_y')
            w = infoform.cleaned_data.get('b_width')
            h = infoform.cleaned_data.get('b_height')
            profile.crop_banner_picture(photo,x,y,w,h)
          profile.username = infoform.cleaned_data.get('username')
          profile.biography = infoform.cleaned_data.get('biography')
          profile.save()
          
          redirecturl = request.POST.get('redirect', '/')

          return redirect(redirecturl)

    else:
      form = TweetForm()
      infoform = PersonalInfoForm()

    return render(request, 'profile.html', {'form': form, 'infoform': infoform, 'user': user})
  else:
    return redirect('/')

@login_required
def profile_tabs(request, username, tab):
  if request.user.is_authenticated:
    user = User.objects.get(username=username)
    liked = Tweet.objects.all().filter(likes=user.twitterprofile)
    form = TweetForm()
    infoform = PersonalInfoForm()
    return render(request, 'profile.html', {'form': form, 'infoform': infoform, 'user': user, 'liked': liked, 'tab': tab})
  else:
    return redirect('/')


@login_required
def profile_settings(request):
  if request.user.is_authenticated:
    return render(request, 'settings.html', {'user': request.user})
  else:
    return redirect('/')

@login_required
def settings_tabs(request, tab):
    if request.user.is_authenticated:

        form = None

        #screen name change
        if tab == 'screen_name':
            if request.method == 'POST':
                form = ChangeUsernameForm(request.POST or None)
                if form.is_valid():
                    if form.clean_username():
                        profile = request.user.twitterprofile
                        profile.username = form.cleaned_data['username']
                        profile.save()
            else:
                form = ChangeUsernameForm()

        #phone number change
        elif tab == 'phone':
            if request.method == 'POST':
                form = ChangePhoneForm(request.POST or None)
                if form.is_valid():
                    profile = request.user.twitterprofile
                    profile.phone_number = form.cleaned_data['phone_number']
                    profile.save()
            else:
                form = ChangePhoneForm()

        #email change
        elif tab == 'email':
            if request.method == 'POST':
                form = ChangeEmailForm(request.POST or None)
                if form.is_valid():
                    if form.clean_email():
                        request.user.email = form.cleaned_data['email']
                        request.user.save()
            else:
                form = ChangeEmailForm()

        #password change
        if tab == 'password':
            if request.method == 'POST':
                form = ChangePasswordForm(request.POST or None)
                if form.is_valid():
                    request.user.password = form.cleaned_data['password1']
                    request.user.save()
            else:
                form = ChangePasswordForm()

        #privacy change
        if tab == 'deactivateprivacy':
            profile = request.user.twitterprofile
            profile.private = False
            profile.save()
            return redirect('/settings/privacy')
        
        if tab == 'activateprivacy':
            profile = request.user.twitterprofile
            profile.private = True
            profile.save()
            return redirect('/settings/privacy')

        
        return render(request, 'settings_tabs.html', {'tab': tab, 'form': form, 'user': request.user})
    else:
        return redirect('/')

def frontpage(request):
  if request.user.is_authenticated:
    return redirect('/' + request.user.username + '/') # Change this line
  else:
    if request.method == 'POST':
      if 'signupform' in request.POST:
        signupform = SignupForm(data=request.POST)
        signinform = SigninForm()
        
        if signupform.is_valid():
          username = signupform.cleaned_data['username']
          password = signupform.cleaned_data['password1']
          signupform.save()
          user = authenticate(username=username, password=password)
          profile = user.twitterprofile
          profile.username = signupform.cleaned_data['name']
          profile.save()
          login(request, user)
          return redirect('/')
      else:
        signinform = SigninForm(data=request.POST)
        signupform = SignupForm()
        
        if signinform.is_valid():
          login(request, signinform.get_user())
          return redirect('/')
    else:
        signupform = SignupForm()
        signinform = SigninForm()
  
    return render(request, 'frontpage.html', {'signupform': signupform, 'signinform': signinform})

@login_required
def signout(request):
  logout(request)
  return redirect('/')

twitter_clone/twitter_profile/templates/profile.html
{% extends 'templates/base.html' %}
{% load filters %}
{% load static %}


{% block main %}
<div class="row">

  <div class="col-9 border p-0">
    <div class="container-fluid p-0 mb-3">
    {% if user.twitterprofile.profile_banner %}
    <img src='{{ user.twitterprofile.profile_banner.url }}' class="container-fluid p-0">
    {% else %}
    <img src='{% static 'images/banner.jpg' %}' class="container-fluid p-0">
    {% endif %}
    <div class="container-fluid p-0">
      <div class="container-fluid mt-2 mb-2 d-flex justify-content-end position-relative">
        {% if user.twitterprofile.profile_picture %}
        <a class="d-flex position-absolute ml-3 profile-picture" href="/{{ user.username }}/" style="bottom:0;left:0;">
          <img src='{{ user.twitterprofile.profile_picture.url }}' class="w-100 h-100 p-1 bg-light rounded-circle">
        </a>
        {% else %}
        <a class="d-flex position-relative ml-3 profile-picture" href="/{{ user.username }}/" style="bottom:0;left:0;">
          <img src="{% static 'images/profile.jpg' %}" class="w-100 h-100 p-1 bg-light rounded-circle">
        </a>
        {% endif %}
            <!-- Button trigger modal -->
        {% ifequal request.user user %}
        <button type="button" class="btn btn-outline-primary font-weight-bold" data-toggle="modal" data-target="#infomodel">
            Edit Profile
        </button>
        
        <!-- Modal -->
        <div class="modal fade" id="infomodel" tabindex="-1" role="dialog" aria-labelledby="infomodel" aria-hidden="true">
          <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Edit Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="infophoto">
                  <form method="post" action="/{{ request.user.username }}/" enctype="multipart/form-data" id="formUpload">
                    <div v-if="!cropperActive" class="container-fluid position-relative p-0">
                      <label for="id_banner_picture" class="preview container-fluid p-0 position-relative">
                          <div class="position-absolute justify-content-center align-center align-items-center d-flex w-100 h-100 rounded-circle">
                              <span class="oi oi-camera-slr h4 m-0 text-light p-3 rounded-circle"></span>
                          </div>
                          <img v-if="banner_thumb" :src="banner_thumb" class="w-100 h-100 p-1"/>
                      </label>
                      <label for="id_profile_picture" class="preview d-flex position-absolute profile-picture ml-3" style="bottom:-50px;">
                          <div class="position-absolute justify-content-center align-center align-items-center d-flex w-100 h-100 rounded-circle">
                              <span class="oi oi-camera-slr h4 m-0 text-light p-3 rounded-circle"></span>
                          </div>
                          <img v-if="profile_thumb" :src="profile_thumb" class="w-100 h-100 p-1 bg-light rounded-circle" />
                      </label>
                    </div>
                    <cropper
                      v-if="banner_url" 
                      :src="banner_url"
                      :stencil-props="{ aspectRatio: 3/1 }"
                      ref="cropper"
                      @change="banner_change"
                      class="mb-2 cropper"
                    ></cropper>
                    <div class="mb-4 d-flex justify-content-end">
                      <button v-if="banner_url" type="button" class="btn btn-primary" @click="banner_apply">
                          Apply
                      </button>
                    </div>
                    <cropper
                      v-if="profile_url" 
                      :src="profile_url"
                      :stencil-props="{ aspectRatio: 1/1 }"
                      ref="cropper"
                      @change="profile_change"
                      class="mb-2 cropper"
                    ></cropper>
                    <div class="mb-4 d-flex justify-content-end">
                      <button v-if="profile_url" type="button" class="btn btn-primary" @click="profile_apply">
                          Apply
                      </button>
                    </div>
                    {% csrf_token %}
                    {{ infoform.banner_picture }}
                    {{ infoform.profile_picture }}
                    {{ infoform.p_x }}
                    {{ infoform.p_y }}
                    {{ infoform.p_width }}
                    {{ infoform.p_height }}
                    {{ infoform.b_x }}
                    {{ infoform.b_y }}
                    {{ infoform.b_width }}
                    {{ infoform.b_height }}
                    <div class="mb-4">
                      <div class="input-label" v-bind:class="{ 'input-label-active': user_focus }">
                        Name<small class="float-right p-0 m-0"><span v-text="(max_user - username.length)"></span>/<span v-text="max_user"></span></small>
                      </div>
                      {{ infoform.username }}
                    </div>
                    <div class="mb-4">
                      <div class="input-label" v-bind:class="{ 'input-label-active': bio_focus }">
                        Bio<small class="float-right p-0 m-0"><span v-text="(max_bio - bio.length)"></span>/<span v-text="max_bio"></span></small>
                      </div>
                      {{ infoform.biography }}
                    </div>
                    <input type="hidden" value="{{ request.path }}" name="redirect">
                    <input type="submit" value="Save" name="infoform" class="btn btn-primary float-right">
                  </form>
              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>  
        {% endifequal %}    
      </div>
      <div class="container-fluid mt-1 mb-1">
          <h4 class="m-0 font-weight-bold">{{ user.twitterprofile.username }}</h4>
          <h6 class="m-0 text-secondary font-italic">@{{ user.username }}</h6>
      </div>
      <div class="container-fluid">
          <p class="mt-1 mb-1">{{ user.twitterprofile.biography }}</p>
      </div>
      <div class="container-fluid">
          {% if user.twitterprofile.phone_number %}
          <p class="text-secondary mt-1 mb-1"><span class="oi oi-phone mr-2"></span>{{ user.twitterprofile.phone_number }}</p>
          {% endif %}
          <p class="text-secondary mt-1 mb-1"><span class="oi oi-calendar mr-2"></span>Joined {{ user.date_joined|date:"F j, Y" }}</p>
      </div>
    </div>
    </div>

    <div class="container-fluid border-top pt-3 pb-3 border-bottom">
      <b>{{ user.twitterprofile.follows.count }}</b> <a href="/{{ user.username }}/follows/" class="text-secondary font-weight-normal mr-3">Following</a>
      <b>{{ user.twitterprofile.followed_by.count }}</b> <a href="/{{ user.username }}/followers/" class="text-secondary font-weight-normal">Followers</a>
    </div>
    {% ifnotequal request.user user %}

      {% if request.user.twitterprofile in user.twitterprofile.followed_by.all %}
        <a href="/{{ user.username }}/stopfollow/" class="btn btn-danger">Stop follow</a>
      {% else %}
        <a href="/{{ user.username }}/follow/" class="btn btn-success">Follow</a>
      {% endif %}
    {% endifnotequal %}



    <!-- Feed -->
    <nav class="nav nav-justified border-bottom">
        <button onclick="profileTab('')" class="profile-tab p-2 font-weight-bold nav-item btn {% if not tab %}active{% endif %}">Tweets</button>
        <button onclick="profileTab('')" class="profile-tab p-2 font-weight-bold nav-item btn">Tweets & Replies</button>
        <button onclick="profileTab('')" class="profile-tab p-2 font-weight-bold nav-item btn">Media</button>
        <button onclick="profileTab('likes')" class="profile-tab p-2 font-weight-bold nav-item btn {% if tab == 'likes' %}active{% endif %}">Likes</button>
    </nav>
    <div>
        {% if request.user == user or request.user.twitterprofile in user.twitterprofile.followed_by.all and user.twitterprofile.private or not user.twitterprofile.private  %}
          {% if tab %}
            {% if liked.all %}
              {% get_tweets liked.all request.user form %}
            {% endif %}
          {% else %}
            {% if user.tweets.all %}
              {% get_tweets user.tweets.all request.user form %}
            {% endif %}
          {% endif %}
        {% else %}
        <p>This user's profile is set to Private.</p>
        {% endif %}
    </div>

  </div>


</div>

<script>
  const vm = new Vue({
    el: '#infophoto',
    data() {
      return {
        banner_coordinates: {
          width: 0,
          height: 0,
          left: 0,
          top: 0
        },
        profile_coordinates: {
          width: 0,
          height: 0,
          left: 0,
          top: 0
        },
        profile_thumb: '{{ user.twitterprofile.profile_picture.url }}',
        banner_thumb: '{% if user.twitterprofile.profile_banner %}{{ user.twitterprofile.profile_banner.url }}{% else %}{% static 'images/banner.jpg' %}{% endif %}',
        profile_url: null,
        banner_url: null,
        username: '{{ user.twitterprofile.username }}',
        max_user: 50,
        user_focus:false,
        bio: '{{ user.twitterprofile.biography }}',
        bio_focus:false,
        max_bio: 160,
        cropperActive: false,
      }
    },
    methods: {
      onBannerChange(e) {
        const file = e.target.files[0];
        this.banner_url = URL.createObjectURL(file);
        this.cropperActive = true;
      },
      onProfileChange(e) {
        const file = e.target.files[0];
        this.profile_url = URL.createObjectURL(file);
        this.cropperActive = true;
      },
      profile_change({coordinates, canvas}) {
        this.profile_coordinates = coordinates
        this.profile_thumb = canvas.toDataURL()
      },
      banner_change({coordinates, canvas}) {
        this.banner_coordinates = coordinates
        this.banner_thumb = canvas.toDataURL()
      },
      banner_apply() {
        this.banner_url = null;
        this.cropperActive = false;
		  },
      profile_apply() {
        this.profile_url = null;
        this.cropperActive = false;
		  }
    }
  });

  function profileTab (tab){
    history.replaceState(null,null, "/{{ user.username }}/" + tab);
    location.reload();
  }

</script>
{% endblock %}

twitter_clone/twitter_profile/templates/settings.html
{% extends 'templates/base.html' %}


{% block main %}
<div class="container-fluid">
        <div class="row">
                <div class="col-4 border-right">
                    <div class="border px-3 py-3 h5 m-0">
                        <strong>Settings</strong>
                    </div>
                    <div class="border px-3 py-3 h5 m-0">
                        <strong>@{{ user.username }}</strong>
                    </div>
                    <div class="list-group" id="list-tab" role="tablist">
                        <a class="list-group-item list-group-item-action" id="list-home-list" href="/settings/account" role="tab" aria-controls="home">Account</a>
                        <a class="list-group-item list-group-item-action" id="list-profile-list" href="/settings/privacy" role="tab" aria-controls="profile">Privacy & Safety</a>
                        <a class="list-group-item list-group-item-action" id="list-messages-list" href="/settings/notifications" role="tab" aria-controls="messages">Notifications</a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" href="/settings/preferences" role="tab" aria-controls="settings">Content Preferences</a>
                    </div>
                </div>
                <div class="col-8">
                  <div class="tab-content" id="nav-tabContent">
                        {% block settings %}
                        {% endblock %}
                  </div>
                </div>
              </div>
</div>
{% endblock %}

twitter_clone/twitter_profile/templates/users.html
{% extends 'base.html' %}

{% block main %}
<div>
  <h1>{{ title }}</h1>
  <ul>
    {% for twitter_clone in twitterprofiles %}
      <li><a href="/{{ twitter_clone.user.username }}/">@{{ twitter_clone.user.username }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}